### ISSUE TITLE
may I ask about your updated version of SKEAF code 

### ISSUE THREAD

**Issue by aaaahxxx** [chenyubi14/quantum_oscill_freq#1]
hi~
your instructions about how to calculate quantum oscillation frequencie is very useful . in REAMED.md of quantum_oscill_freq,you mention that "but I have made some changes to the source for an easier usage. Please download my updated SKEAF version."
please tell me how and where could download your updated SKEAF code , thanks!!
looking forward to you

**Comment by chenyubi14** [comment]
Hi,

Thanks for asking. I uploaded the editted SKEAF files ([skeaf_v2_update4vasp.tar.gz](https://github.com/chenyubi14/quantum_oscill_freq/blob/main/skeaf_v2_update4vasp.tar.gz)). I hope this can resolve the most urgent need.

I am traveling two days, so if you need more codes. I will upload them in the weekend.

Best

**Comment by aaaahxxx** [comment]
hi~
Thanks for  uploading the  editted SKEAF files!!!!!  I have downloaded them and now learn  to do  right calculations .  if you could upload more codes in the future ,it helps. 
And enjoy your trip first!!  Be happy everyday!!!
Best wishes to you !

> Hi,
> 
> Thanks for asking. I uploaded the editted SKEAF files ([skeaf_v2_update4vasp.tar.gz](https://github.com/chenyubi14/quantum_oscill_freq/blob/main/skeaf_v2_update4vasp.tar.gz)). I hope this can resolve the most urgent need.
> 
> I am traveling two days, so if you need more codes. I will upload them in the weekend.
> 
> Best
